/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MortisVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "beneficiary"
      | "cleartextBalanceAtTrigger"
      | "decryptionPending"
      | "decryptionRequestId"
      | "deposit"
      | "inheritanceCallback"
      | "inherited"
      | "lastPing"
      | "owner"
      | "ping"
      | "protocolId"
      | "requestTrigger"
      | "requestWithdraw"
      | "secondsUntilTrigger"
      | "triggerWindow"
      | "triggered"
      | "vaultStatus"
      | "withdrawCallback"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecryptionFulfilled"
      | "Deposited"
      | "Inherited"
      | "Pinged"
      | "TriggerRequested"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "beneficiary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cleartextBalanceAtTrigger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionPending",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionRequestId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "inheritanceCallback",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "inherited", values?: undefined): string;
  encodeFunctionData(functionFragment: "lastPing", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "ping", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestTrigger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "secondsUntilTrigger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "triggerWindow",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "triggered", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vaultStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCallback",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "beneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cleartextBalanceAtTrigger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionPending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "inheritanceCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "inherited", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastPing", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ping", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestTrigger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "secondsUntilTrigger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "triggered", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCallback",
    data: BytesLike
  ): Result;
}

export namespace DecryptionFulfilledEvent {
  export type InputTuple = [requestID: BigNumberish];
  export type OutputTuple = [requestID: bigint];
  export interface OutputObject {
    requestID: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InheritedEvent {
  export type InputTuple = [beneficiary: AddressLike, amount: BigNumberish];
  export type OutputTuple = [beneficiary: string, amount: bigint];
  export interface OutputObject {
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PingedEvent {
  export type InputTuple = [
    owner: AddressLike,
    timestamp: BigNumberish,
    secondsRemaining: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    timestamp: bigint,
    secondsRemaining: bigint
  ];
  export interface OutputObject {
    owner: string;
    timestamp: bigint;
    secondsRemaining: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TriggerRequestedEvent {
  export type InputTuple = [caller: AddressLike, requestId: BigNumberish];
  export type OutputTuple = [caller: string, requestId: bigint];
  export interface OutputObject {
    caller: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MortisVault extends BaseContract {
  connect(runner?: ContractRunner | null): MortisVault;
  waitForDeployment(): Promise<this>;

  interface: MortisVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  beneficiary: TypedContractMethod<[], [string], "view">;

  cleartextBalanceAtTrigger: TypedContractMethod<[], [bigint], "view">;

  decryptionPending: TypedContractMethod<[], [boolean], "view">;

  decryptionRequestId: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<[], [void], "payable">;

  inheritanceCallback: TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  inherited: TypedContractMethod<[], [boolean], "view">;

  lastPing: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ping: TypedContractMethod<[], [void], "nonpayable">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  requestTrigger: TypedContractMethod<[], [void], "nonpayable">;

  requestWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  secondsUntilTrigger: TypedContractMethod<[], [bigint], "view">;

  triggerWindow: TypedContractMethod<[], [bigint], "view">;

  triggered: TypedContractMethod<[], [boolean], "view">;

  vaultStatus: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        _owner: string;
        _beneficiary: string;
        _triggered: boolean;
        _inherited: boolean;
        _decryptionPending: boolean;
        _lastPing: bigint;
        _triggerWindow: bigint;
        _secondsLeft: bigint;
        _ethHeld: bigint;
      }
    ],
    "view"
  >;

  withdrawCallback: TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "beneficiary"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cleartextBalanceAtTrigger"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decryptionPending"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "decryptionRequestId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "inheritanceCallback"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "inherited"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastPing"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ping"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestTrigger"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "secondsUntilTrigger"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "triggerWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "triggered"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "vaultStatus"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        _owner: string;
        _beneficiary: string;
        _triggered: boolean;
        _inherited: boolean;
        _decryptionPending: boolean;
        _lastPing: bigint;
        _triggerWindow: bigint;
        _secondsLeft: bigint;
        _ethHeld: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawCallback"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "DecryptionFulfilled"
  ): TypedContractEvent<
    DecryptionFulfilledEvent.InputTuple,
    DecryptionFulfilledEvent.OutputTuple,
    DecryptionFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Inherited"
  ): TypedContractEvent<
    InheritedEvent.InputTuple,
    InheritedEvent.OutputTuple,
    InheritedEvent.OutputObject
  >;
  getEvent(
    key: "Pinged"
  ): TypedContractEvent<
    PingedEvent.InputTuple,
    PingedEvent.OutputTuple,
    PingedEvent.OutputObject
  >;
  getEvent(
    key: "TriggerRequested"
  ): TypedContractEvent<
    TriggerRequestedEvent.InputTuple,
    TriggerRequestedEvent.OutputTuple,
    TriggerRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "DecryptionFulfilled(uint256)": TypedContractEvent<
      DecryptionFulfilledEvent.InputTuple,
      DecryptionFulfilledEvent.OutputTuple,
      DecryptionFulfilledEvent.OutputObject
    >;
    DecryptionFulfilled: TypedContractEvent<
      DecryptionFulfilledEvent.InputTuple,
      DecryptionFulfilledEvent.OutputTuple,
      DecryptionFulfilledEvent.OutputObject
    >;

    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Inherited(address,uint64)": TypedContractEvent<
      InheritedEvent.InputTuple,
      InheritedEvent.OutputTuple,
      InheritedEvent.OutputObject
    >;
    Inherited: TypedContractEvent<
      InheritedEvent.InputTuple,
      InheritedEvent.OutputTuple,
      InheritedEvent.OutputObject
    >;

    "Pinged(address,uint256,uint256)": TypedContractEvent<
      PingedEvent.InputTuple,
      PingedEvent.OutputTuple,
      PingedEvent.OutputObject
    >;
    Pinged: TypedContractEvent<
      PingedEvent.InputTuple,
      PingedEvent.OutputTuple,
      PingedEvent.OutputObject
    >;

    "TriggerRequested(address,uint256)": TypedContractEvent<
      TriggerRequestedEvent.InputTuple,
      TriggerRequestedEvent.OutputTuple,
      TriggerRequestedEvent.OutputObject
    >;
    TriggerRequested: TypedContractEvent<
      TriggerRequestedEvent.InputTuple,
      TriggerRequestedEvent.OutputTuple,
      TriggerRequestedEvent.OutputObject
    >;

    "Withdrawn(address,uint64)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
